apiVersion: v1
kind: Pod
metadata:
  name: sc-pvc-pod
spec:
  containers:
   - name: myvolumes-container
     image: alpine
     imagePullPolicy: IfNotPresent
     command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
     volumeMounts:
      - name: pv
        mountPath: "/my-pv-path"
  volumes:
   - name: pv
     persistentVolumeClaim:
       claimName: my-pvc1
