apiVersion: v1
kind: Service
metadata:
  name: tomcatsvc
  labels:
    app: tomcatapp
spec:
  type: NodePort   
  ports:
  - port: 8080  # inside container
    nodePort: 30001 #expose , if dont give takes default
    protocol: TCP
  selector:
    app: tomcat

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcatrc
spec:
  replicas: 3
  selector:
    app: tomcat
  template:
    metadata:
      name: tomcat
      labels:
        pod: tomcatrc
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: lerndevops/tomcat:8.5.47
        ports:
        - containerPort: 8080