apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
  labels:
    app: npapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: npapp
  template:
    metadata:
      labels:
        app: npapp 
    spec:
      containers:
      - name: myapp-cont
        image: lerndevops/samplepyapp:v2
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: pyapp
spec:
  type: NodePort
  selector:
    app: npapp
  ports:
   - protocol: TCP
     port: 80
     targetPort: 3000
     #nodePort: 30005
