apiVersion: apps/v1
kind: Deployment
metadata:
  name: cipapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cipapp
  template:
    metadata:
      labels:
        app: cipapp
    spec:
      containers:
      - name: myapp-cont
        image: lerndevops/samplepyapp:v1
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: cipapp
spec:
  type: ClusterIP  ## this is default if we do not type in service definition
  selector:
    app: cipapp
  ports:
   - protocol: TCP
     port: 80
     targetPort: 3000
