apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mying-rule
  annotations:
    #kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /electronics
          backend:
            serviceName: myshop-electronics-svc
            servicePort: 80
        - path: /fashion
          backend:
            serviceName: myshop-fashion-svc
            servicePort: 80
        - path: /travel
          backend:
            serviceName: myshop-travel-svc
            servicePort: 80
