apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: ZXhhbXBsZS11c2Vy
  password: ZXhhbXBsZS1wYXNzd29yZA==

---

apiVersion: v1
kind: Pod
metadata:
  name: secret-ex1-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    volumeMounts:             #We mount our volume
    - name: myvol
      mountPath: "/apps/secrets"
      readOnly: true
  volumes:                    #We use the volume and defined our secret
  - name: myvol
    secret:
      secretName: mysecret
