---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi

---

kind: Pod
apiVersion: v1
metadata:
  name: devpod
  labels:
    app: web
spec:
  volumes:
    - name: sec-vol
      secret:
         secretName: test-secret
  containers:
    - name: cont1
      image: tomcat
      ports:
        - containerPort: 8080
      volumeMounts:
         - name: sec-vol
           mountPath: /etc/sec-data


---

kind: Pod
apiVersion: v1
metadata:
  name: devpod1
  labels:
    app: myapp
spec:
  containers:
    - name: cont1
      image: tomcat
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: test-secret

---

kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  labels:
    app: myapp
spec:
  containers:
    - name: cont1
      image: tomcat
      ports:
        - containerPort: 8080
      env:
        - name: dbuser
          valueFrom:
            secretKeyRef:
               name: test-secret
               key: username
        - name: dbpwd
          valueFrom:
            secretKeyRef:
               name: test-secret
               key: password
